title: Hamravesh Restful API
description: A breif fo Hamravesh Restful API
theme: just-the-docs

plugins:
  - jekyll-tabs

url: https://ham-rest.github.io

aux_links:
  Hamravesh: https://hamravesh.com/

collections:
  sections:
    output: true
  extra:
    output: true

just_the_docs:
  collections:
    sections:
      name: Sections
    extra:
      name: Extra

favicon_ico: "/assets/images/favicon.png"

logo: "/assets/images/logo.png"

heading_anchors: true
color_scheme: dark

footer_content: "Copyright &copy; 2024-2024 <a href=\"mailto:otahmasebii@gmail.com\">Mohammad Tahmasebi</a>."

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ham-rest/ham-rest.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Postman Collection
    url: https://github.com/ham-rest/ham-rest.github.io/blob/main/Hamravesh.postman_collection.json
    hide_icon: false
    opens_in_new_tab: true

