title: Hamravesh Restful API
description: A breif fo Hamravesh Restful API
theme: just-the-docs

plugins:
  - jekyll-tabs

url: https://ham-rest.github.io

aux_links:
  Github Repo: https://github.com/ham-rest/ham-rest.github.io
